# Generated by Django 2.2 on 2019-08-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Inprocess', 'Inprocess')], default='', help_text='State of the project', max_length=10),
        ),
    ]
