# Generated by Django 2.2 on 2019-08-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190831_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolset',
            name='name',
            field=models.CharField(blank=True, help_text='Program/Language', max_length=50, null=True),
        ),
    ]
