# Generated by Django 2.2 on 2019-08-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190831_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolset',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='toolset',
            name='library',
        ),
        migrations.AlterField(
            model_name='toolset',
            name='name',
            field=models.CharField(blank=True, help_text='Program, Library or Framework', max_length=50, null=True),
        ),
    ]
